// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS_DotNet02_Online_Naumenko.Data.Contexts.MainContext;

#nullable disable

namespace TMS_DotNet02_Online_Naumenko.Data.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20220531132807_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FileExtensionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileExtensionId");

                    b.HasIndex("UserId");

                    b.ToTable("Files", "file");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3139),
                            FileExtensionId = 1,
                            ModificationDate = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3140),
                            Name = "Bitcoin",
                            Path = "https://static.euronews.com/articles/stories/06/70/41/64/1100x619_cmsv2_5f541c98-76be-5006-884a-6aeb44d3ea5d-6704164.jpg",
                            Slug = "bitcoin",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3142),
                            FileExtensionId = 1,
                            ModificationDate = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3142),
                            Name = "Bayraktar drone",
                            Path = "https://static.euronews.com/articles/stories/06/73/86/18/773x435_cmsv2_21a9e255-64c6-5f6d-b2b7-6cb91ffd959c-6738618.jpg",
                            Slug = "bayraktar-drone",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3143),
                            FileExtensionId = 1,
                            ModificationDate = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3143),
                            Name = "Russian troops",
                            Path = "https://static.euronews.com/articles/stories/06/73/98/06/773x435_cmsv2_3bca83fd-4dfd-55c1-abee-d0e4a5ce92ce-6739806.jpg",
                            Slug = "russian-troops",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3145),
                            FileExtensionId = 1,
                            ModificationDate = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3145),
                            Name = "Liverpool fans",
                            Path = "https://static.euronews.com/articles/stories/06/73/99/06/773x435_cmsv2_28e39cf9-5c2e-5180-bc01-527de916c93c-6739906.jpg",
                            Slug = "liverpool-fans",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.FileExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FileExtensions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "jpg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "png"
                        });
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.FileTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("TermId");

                    b.ToTable("FileTerms");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Site name",
                            Value = "News Portal"
                        });
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ReadingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", "post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Cryptocurrencies resumed their slide on Monday, giving up the gains they had eked out over the weekend as regulators continued to circle.European officials reiterated warnings of risks posed by cryptocurrencies.Bitcoin fell 5 per cent to around $29,700 (€28,500) on Monday in Asian trade, sliding alongside stocks because of worries about high inflation and rising interest rates.The world's largest cryptocurrency has lost around a fifth of its value so far this month, as the spectacular collapse of TerraUSD, a so-called stablecoin, has roiled crypto markets already falling amid a broad selling of risky investments.",
                            Date = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3190),
                            Excerpt = "Cryptocurrencies resumed their slide on Monday, giving up the gains they had eked out over the weekend as regulators continued to circle.European officials reiterated warnings of risks posed by cryptocurrencies.Bitcoin fell 5 per cent to around $29,700 (€28,500) on Monday in Asian trade, sliding alongside stocks because of worries about high inflation and rising interest rates.The world's largest cryptocurrency has lost around a fifth of its value so far this month, as the spectacular collapse of TerraUSD, a so-called stablecoin, has roiled crypto markets already falling amid a broad selling of risky investments.",
                            FileId = 1,
                            ModificationDate = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3190),
                            PostStatusId = 1,
                            ReadingTime = "2 min",
                            Slug = "bitcoin-slips-back-below-30000-as-european-regulators-renew-crypto-warnings-after-terra-luna-crash",
                            Title = "Bitcoin slips back below $30,000 as European regulators renew crypto warnings after Terra Luna crash",
                            TypeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Russian and Ukrainian troops engaged in close-quarter combat in an eastern Ukraine city on Sunday as Moscow's soldiers, supported by intense shelling, attempted to gain a strategic foothold in the region while facing fierce Ukrainian resistance.",
                            Date = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3193),
                            Excerpt = "Russian and Ukrainian troops engaged in close-quarter combat in an eastern Ukraine city on Sunday as Moscow's soldiers, supported by intense shelling, attempted to gain a strategic foothold in the region while facing fierce Ukrainian resistance.",
                            FileId = 3,
                            ModificationDate = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3193),
                            PostStatusId = 1,
                            ReadingTime = "2 min",
                            Slug = "russian-troops-storm-sievierodonetsk-as-donbas-suffers-heavy-bombardment",
                            Title = "Russian troops storm Sievierodonetsk as Donbas suffers heavy bombardment",
                            TypeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Riot police fired tear gas and pepper spray at Liverpool supporters forced to endure long waits to get into the Champions League final amid logistical chaos on Saturday.The start of the showpiece game of the European football season, in which Liverpool lost 1-0 to Real Madrid, was delayed for 37 minutes and kicked off as security was still struggling with the flow of frustrated supporters into the Stade de France.UEFA claimed there were thousands of ticketless fans trying to gain access to the 80, 000 - plus capacity French national stadium but it did not identify where they were from.French Interior Minister Gérald Darmanin claimed stewards were assaulted by the supporters of the English side who forced entry without tickets or with counterfeit tickets.",
                            Date = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3195),
                            Excerpt = "Riot police fired tear gas and pepper spray at Liverpool supporters forced to endure long waits to get into the Champions League final amid logistical chaos on Saturday.The start of the showpiece game of the European football season, in which Liverpool lost 1-0 to Real Madrid, was delayed for 37 minutes and kicked off as security was still struggling with the flow of frustrated supporters into the Stade de France.UEFA claimed there were thousands of ticketless fans trying to gain access to the 80, 000 - plus capacity French national stadium but it did not identify where they were from.French Interior Minister Gérald Darmanin claimed stewards were assaulted by the supporters of the English side who forced entry without tickets or with counterfeit tickets.",
                            FileId = 4,
                            ModificationDate = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3195),
                            PostStatusId = 1,
                            ReadingTime = "1 min",
                            Slug = "liverpool-fans-pepper-sprayed-by-french-police-in-stadium-entry-chaos",
                            Title = "Liverpool fans pepper-sprayed by French police in stadium entry chaos",
                            TypeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Europe's frantic search for alternatives to Russian energy has dramatically increased the demand — and price — for Norway's oil and gas.But the continent's second-biggest natural gas supplier is now fending off accusations that it is profiting from the war in Ukraine.Polish Prime Minister Mateusz Morawiecki, who is looking to the Scandinavian country to replace some of the gas Poland used to get from Russia, said Norway's 'gigantic' oil and gas profits are 'indirectly preying on the war'. He urged Norway to use that windfall to support the hardest-hit countries, mainly Ukraine.The comments last week touched a nerve, even as some Norwegians wonder whether they're doing enough to combat Kremlin's war by increasing economic aid to Ukraine and helping neighbouring countries end their dependence on Russian energy.",
                            Date = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3196),
                            Excerpt = "Europe's frantic search for alternatives to Russian energy has dramatically increased the demand — and price — for Norway's oil and gas.But the continent's second-biggest natural gas supplier is now fending off accusations that it is profiting from the war in Ukraine.Polish Prime Minister Mateusz Morawiecki, who is looking to the Scandinavian country to replace some of the gas Poland used to get from Russia, said Norway's 'gigantic' oil and gas profits are 'indirectly preying on the war'. He urged Norway to use that windfall to support the hardest-hit countries, mainly Ukraine.The comments last week touched a nerve, even as some Norwegians wonder whether they're doing enough to combat Kremlin's war by increasing economic aid to Ukraine and helping neighbouring countries end their dependence on Russian energy.",
                            FileId = 2,
                            ModificationDate = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3196),
                            PostStatusId = 1,
                            ReadingTime = "1 min",
                            Slug = "norways-energy-sales-growth-spurs-accusations-of-profiting-from-war-demands-for-help",
                            Title = "Norway's energy sales growth spurs accusations of profiting from war, demands for help",
                            TypeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "test content",
                            Date = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3197),
                            Excerpt = "test content",
                            FileId = 1,
                            ModificationDate = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3198),
                            PostStatusId = 1,
                            ReadingTime = "1 min",
                            Slug = "test-news",
                            Title = "Test news",
                            TypeId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.PostTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("TermId");

                    b.ToTable("PostTerms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PostId = 2,
                            TermId = 1
                        },
                        new
                        {
                            Id = 2,
                            PostId = 2,
                            TermId = 3
                        },
                        new
                        {
                            Id = 3,
                            PostId = 1,
                            TermId = 1
                        },
                        new
                        {
                            Id = 4,
                            PostId = 1,
                            TermId = 2
                        },
                        new
                        {
                            Id = 5,
                            PostId = 3,
                            TermId = 2
                        },
                        new
                        {
                            Id = 6,
                            PostId = 4,
                            TermId = 2
                        },
                        new
                        {
                            Id = 7,
                            PostId = 4,
                            TermId = 3
                        });
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parent")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TermTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Terms", "term");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Money",
                            Parent = 0,
                            Slug = "Money",
                            TermTypeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Politic",
                            Parent = 0,
                            Slug = "Politic",
                            TermTypeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bitcoin",
                            Parent = 1,
                            Slug = "Bitcoin",
                            TermTypeId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users", "user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@test.test",
                            Login = "admin",
                            Name = "Super User",
                            PasswordHash = "$2a$11$hmfTa1iFuPbr4O83CClksurk83/oDbXi5WEMP/yqgqpKLbZ0dF93.",
                            RegisteredAt = new DateTime(2022, 5, 31, 13, 28, 7, 393, DateTimeKind.Utc).AddTicks(3110),
                            UserRoleId = 1
                        });
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "editor"
                        });
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.File", b =>
                {
                    b.HasOne("TMS_DotNet02_Online_Naumenko.Data.Models.FileExtension", "FileExtension")
                        .WithMany("Files")
                        .HasForeignKey("FileExtensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS_DotNet02_Online_Naumenko.Data.Models.User", "User")
                        .WithMany("Files")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileExtension");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.FileTerm", b =>
                {
                    b.HasOne("TMS_DotNet02_Online_Naumenko.Data.Models.File", "File")
                        .WithMany("FileTerms")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS_DotNet02_Online_Naumenko.Data.Models.Term", "Term")
                        .WithMany("FileTerms")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.Post", b =>
                {
                    b.HasOne("TMS_DotNet02_Online_Naumenko.Data.Models.File", "File")
                        .WithMany("Posts")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS_DotNet02_Online_Naumenko.Data.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.PostTerm", b =>
                {
                    b.HasOne("TMS_DotNet02_Online_Naumenko.Data.Models.Post", "Post")
                        .WithMany("PostTerms")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS_DotNet02_Online_Naumenko.Data.Models.Term", "Term")
                        .WithMany("PostTerms")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.Term", b =>
                {
                    b.HasOne("TMS_DotNet02_Online_Naumenko.Data.Models.User", "User")
                        .WithMany("Terms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.User", b =>
                {
                    b.HasOne("TMS_DotNet02_Online_Naumenko.Data.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.File", b =>
                {
                    b.Navigation("FileTerms");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.FileExtension", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.Post", b =>
                {
                    b.Navigation("PostTerms");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.Term", b =>
                {
                    b.Navigation("FileTerms");

                    b.Navigation("PostTerms");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.User", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Posts");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("TMS_DotNet02_Online_Naumenko.Data.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
